export const Routes = {
  Auth: {
    SignIn: 'SignIn',
    SignUp: 'SignUp',
    VerificationPage: 'VerificationPage',
    PasswordReset: 'PasswordReset',
    Agreement: 'Agreement',
  },
  Tabs: {
    DashboardTab: 'DashboardTab',
    ProxiesTab: 'ProxiesTab',
    OrdersTab: 'OrdersTab',
    SettingsTab: 'SettingsTab',
  },
  App: {
    Dashboard: 'Dashboard',
    Settings: 'Settings',
    Account: 'Account',
    ChangePassword: 'ChangePassword',
    WriteUs: 'WriteUs',
    FAQ: 'FAQ',
    ProxyCheck: 'ProxyCheck',
    ProxyCheckResult: 'ProxyCheckResult',
    SpeedTest: 'SpeedTest',
    SpeedTestResult: 'SpeedTestResult',
    Orders: 'Orders',
    Proxy: 'Proxy',
    Wallet: 'Wallet',
    NewOrderPage: 'NewOrderPage',
    SelectCountry: 'SelectCountry',
    Proxies: 'Proxies',
  },
};
